### ISSUE TITLE
Panel Not Working In 'grafana-4.6.0-beta2' Build

### ISSUE THREAD

**Issue by MarkTurbo** [briangann/grafana-gauge-panel#26]
I just installed the latest Grafana Beta, and updated all my plugins, but the D3 Gauge panel no longer works. All my instances of the panel on my dashboards have the following error...

Message:
d3.select is not a function

Stack Trace:
TypeError: d3.select is not a function
    at D3GaugePanelCtrl.renderGauge (http://10.12.177.41:8083/public/plugins/briangann-gauge-panel/ctrl.js:279:26)
    at render (http://10.12.177.41:8083/public/plugins/briangann-gauge-panel/ctrl.js:469:20)
    at o.eval (http://10.12.177.41:8083/public/plugins/briangann-gauge-panel/ctrl.js:472:15)
    at o.emit (http://10.12.177.41:8083/public/build/vendor.5da12e656ad39d359b66.js:15:521182)
    at t.emit (http://10.12.177.41:8083/public/build/app.7284db05d4e6adf870ef.js:1:29207)
    at D3GaugePanelCtrl.t.render (http://10.12.177.41:8083/public/build/0.f26a6d0245b482a353c3.js:1:16894)
    at D3GaugePanelCtrl.onDataReceived (http://10.12.177.41:8083/public/plugins/briangann-gauge-panel/ctrl.js:636:20)
    at o.emit (http://10.12.177.41:8083/public/build/vendor.5da12e656ad39d359b66.js:15:520749)
    at t.emit (http://10.12.177.41:8083/public/build/app.7284db05d4e6adf870ef.js:1:29207)
    at D3GaugePanelCtrl.e.handleQueryResult (http://10.12.177.41:8083/public/build/0.f26a6d0245b482a353c3.js:7:19860)

I also tried adding a new D3 Gauge to a new dashboard, but get the same error. Any ideas what's going on?

**Comment by briangann** [comment]
I'll try out the beta, I'm running 4.5.2-1 currently.

**Comment by stullii** [comment]
It's working fine with 4.6.0 final!
